In [ ]:
# 特征选择
    #采用随机森林方法

#本函数采用随机森林方法，选择出25个主要属性
    #并按25属性重新构造数据框

# 1.参数含义

In [39]:
#def feature_select(df,pro,n_estimators=500,max_features=0.8)
    #df = 为训练集，即df_train
    #pro = 0.99 的含义为前百分之多少的重要，选择因子前多少百分比的重要性
    #n_estimators =100 因子筛选：树数量
    #max_features=0.8 特征选择比例

# 2.读取训练集

In [27]:
#为了测试方便将df_train.csv文件读出来

import pandas as pd
import numpy as np

df=pd.read_csv("Data/df_train.csv", index_col=0) #显示数据第一列为索引值
df.head(10) #查看数据前十行

,TICKER_SYMBOL,END_DATE,C_RESER_CB,DEPOS_IN_OTH_BFI,PRECI_METALS,LOAN_TO_OTH_BANK_FI,TRADING_FA,DERIV_ASSETS,PUR_RESALE_FA,INT_RECEIV,...,DATA_VALUE2170726264,DATA_VALUE2170726265,DATA_VALUE2170726266,DATA_VALUE2210200588,Unnamed: 0.1,Unnamed: 0.1.1,CLOSE_PRICE,TURNOVER_VOL,TURNOVER_VALUE,MARKET_VALUE
0,1,2008-12-31,3.976790e+10,2.150081e+10,9225000.0,9.236676e+09,4.144100e+07,290751000.0,3.473335e+10,1.605636e+09,...,7.135,4.753279,1.349286,10.376667,7.0,7.0,3.019333,9.124747e+08,9.579367e+09,2.776258e+10
1,1,2009-03-31,3.954528e+10,3.281080e+10,7080000.0,9.836695e+09,1.363916e+09,200250000.0,3.247499e+10,1.946312e+09,...,7.135,4.753279,1.349286,8.543333,8.0,8.0,4.658667,1.096579e+09,1.452570e+10,4.283428e+10
2,1,2009-06-30,4.222817e+10,2.081290e+10,5342000.0,7.998342e+09,1.785393e+09,162354000.0,3.795794e+10,1.711397e+09,...,7.135,4.753279,1.349286,7.883333,9.0,9.0,6.302333,8.111175e+08,1.525179e+10,5.794739e+10
3,1,2009-09-30,4.542918e+10,1.781418e+10,4694000.0,8.416666e+09,1.408176e+09,173611000.0,3.602692e+10,1.660956e+09,...,7.135,4.753279,1.349286,8.126667,10.0,10.0,7.248000,9.065716e+08,2.042128e+10,6.664261e+10
4,1,2009-12-31,5.424395e+10,1.559254e+10,3302000.0,5.361139e+09,1.132048e+09,99996000.0,4.092340e+10,1.625700e+09,...,7.135,4.753279,1.349286,8.073333,11.0,11.0,8.006000,5.768548e+08,1.390735e+10,7.360913e+10
5,1,2010-03-31,5.648850e+10,1.124296e+10,2946000.0,5.015728e+09,1.352405e+09,110577000.0,5.720913e+10,1.957240e+09,...,7.135,4.753279,1.349286,8.576667,12.0,12.0,7.582333,6.600740e+08,1.483008e+10,6.971699e+10
6,1,2010-06-30,6.150522e+10,8.844875e+09,2227000.0,5.318759e+09,5.431370e+08,201606000.0,5.496150e+10,2.006350e+09,...,7.135,4.753279,1.349286,8.826667,13.0,13.0,6.257333,6.777460e+08,1.309324e+10,5.974882e+10
7,1,2010-09-30,6.663149e+10,9.861586e+09,786000.0,7.810415e+09,5.540580e+08,320302000.0,7.361530e+10,2.243319e+09,...,7.135,4.753279,1.349286,8.736667,14.0,14.0,5.768667,2.340072e+08,4.103866e+09,5.952404e+10
8,1,2010-12-31,7.658686e+10,8.523729e+09,2000.0,8.475988e+09,1.000000e-05,371734000.0,9.826343e+10,2.121487e+09,...,7.135,4.753279,1.349286,9.160000,15.0,15.0,5.695667,8.653812e+08,1.550966e+10,5.876895e+10
9,1,2011-03-31,7.933548e+10,1.518595e+10,2000.0,7.141762e+09,2.020150e+09,464637000.0,1.369326e+11,2.876637e+09,...,7.135,4.753279,1.349286,9.403333,16.0,16.0,5.327333,5.586879e+08,8.945422e+09,5.497028e+10

In [4]:
df.shape
#属性：数据集共768行，651列

(768, 651)

In [25]:
df.info()
#获取数据信息

<class 'pandas.core.frame.DataFrame'>
Int64Index: 768 entries, 0 to 770
Columns: 651 entries, TICKER_SYMBOL to MARKET_VALUE
dtypes: float64(647), int64(3), object(1)
memory usage: 3.8+ MB

In [5]:
df.columns

Index(['TICKER_SYMBOL', 'END_DATE', 'C_RESER_CB', 'DEPOS_IN_OTH_BFI',
       'PRECI_METALS', 'LOAN_TO_OTH_BANK_FI', 'TRADING_FA', 'DERIV_ASSETS',
       'PUR_RESALE_FA', 'INT_RECEIV',
       ...
       'DATA_VALUE2170726264', 'DATA_VALUE2170726265', 'DATA_VALUE2170726266',
       'DATA_VALUE2210200588', 'Unnamed: 0.1', 'Unnamed: 0.1.1', 'CLOSE_PRICE',
       'TURNOVER_VOL', 'TURNOVER_VALUE', 'MARKET_VALUE'],
      dtype='object', length=651)

# 3.对训练集进行排序

In [61]:
#排序
    # 排序依据为股票代码TICKER_SYMBO + 截至日期END_DATE
df = df.sort_values(by = ['TICKER_SYMBOL' , 'END_DATE'], ascending = True)
    # DataFrame.sort_values(by=‘##’, axis=0, ascending=True, inplace=False, na_position=‘last’)
    #参数说明:    
    #axis:{0 or ‘index’, 1 or ‘columns’}, default 0，默认按照索引排序，即纵向排序，如果为1，则是横向排序    
    #by:str or list of str；如果axis=0，那么by="列名"；如果axis=1，那么by="行名"；  
    #ascending:布尔型，True则升序，可以是[True,False]，即第一字段升序，第二个降序  
    #inplace:布尔型，是否用排序后的数据框替换现有的数据框  
    #kind:排序方法，{‘quicksort’, ‘mergesort’, ‘heapsort’}, default ‘quicksort’。似乎不用太关心  
    #na_position : {‘first’, ‘last’}, default ‘last’，默认缺失值排在最后面 

df.head(10)

,TICKER_SYMBOL,END_DATE,C_RESER_CB,DEPOS_IN_OTH_BFI,PRECI_METALS,LOAN_TO_OTH_BANK_FI,TRADING_FA,DERIV_ASSETS,PUR_RESALE_FA,INT_RECEIV,...,DATA_VALUE2170726265,DATA_VALUE2170726266,DATA_VALUE2210200588,Unnamed: 0.1,Unnamed: 0.1.1,CLOSE_PRICE,TURNOVER_VOL,TURNOVER_VALUE,MARKET_VALUE,target_REVENUE_Q1
0,1,2008-12-31,3.976790e+10,2.150081e+10,9225000.0,9.236676e+09,4.144100e+07,290751000.0,3.473335e+10,1.605636e+09,...,4.753279,1.349286,10.376667,7.0,7.0,3.019333,9.124747e+08,9.579367e+09,2.776258e+10,3.760604e+09
1,1,2009-03-31,3.954528e+10,3.281080e+10,7080000.0,9.836695e+09,1.363916e+09,200250000.0,3.247499e+10,1.946312e+09,...,4.753279,1.349286,8.543333,8.0,8.0,4.658667,1.096579e+09,1.452570e+10,4.283428e+10,3.730246e+09
2,1,2009-06-30,4.222817e+10,2.081290e+10,5342000.0,7.998342e+09,1.785393e+09,162354000.0,3.795794e+10,1.711397e+09,...,4.753279,1.349286,7.883333,9.0,9.0,6.302333,8.111175e+08,1.525179e+10,5.794739e+10,3.623103e+09
3,1,2009-09-30,4.542918e+10,1.781418e+10,4694000.0,8.416666e+09,1.408176e+09,173611000.0,3.602692e+10,1.660956e+09,...,4.753279,1.349286,8.126667,10.0,10.0,7.248000,9.065716e+08,2.042128e+10,6.664261e+10,4.000487e+09
4,1,2009-12-31,5.424395e+10,1.559254e+10,3302000.0,5.361139e+09,1.132048e+09,99996000.0,4.092340e+10,1.625700e+09,...,4.753279,1.349286,8.073333,11.0,11.0,8.006000,5.768548e+08,1.390735e+10,7.360913e+10,4.084252e+09
5,1,2010-03-31,5.648850e+10,1.124296e+10,2946000.0,5.015728e+09,1.352405e+09,110577000.0,5.720913e+10,1.957240e+09,...,4.753279,1.349286,8.576667,12.0,12.0,7.582333,6.600740e+08,1.483008e+10,6.971699e+10,4.411859e+09
6,1,2010-06-30,6.150522e+10,8.844875e+09,2227000.0,5.318759e+09,5.431370e+08,201606000.0,5.496150e+10,2.006350e+09,...,4.753279,1.349286,8.826667,13.0,13.0,6.257333,6.777460e+08,1.309324e+10,5.974882e+10,4.640869e+09
7,1,2010-09-30,6.663149e+10,9.861586e+09,786000.0,7.810415e+09,5.540580e+08,320302000.0,7.361530e+10,2.243319e+09,...,4.753279,1.349286,8.736667,14.0,14.0,5.768667,2.340072e+08,4.103866e+09,5.952404e+10,4.834793e+09
8,1,2010-12-31,7.658686e+10,8.523729e+09,2000.0,8.475988e+09,1.000000e-05,371734000.0,9.826343e+10,2.121487e+09,...,4.753279,1.349286,9.160000,15.0,15.0,5.695667,8.653812e+08,1.550966e+10,5.876895e+10,5.815038e+09
9,1,2011-03-31,7.933548e+10,1.518595e+10,2000.0,7.141762e+09,2.020150e+09,464637000.0,1.369326e+11,2.876637e+09,...,4.753279,1.349286,9.403333,16.0,16.0,5.327333,5.586879e+08,8.945422e+09,5.497028e+10,6.322229e+09

In [7]:
df.shape

(768, 651)

# 4.新增因变量 target_REVENUE_Q1一列

In [80]:
#REVENUE_Q1为第一季度营业收入
#新增的“target_REVENUE_Q1“一列是”REVENUE_Q1“一列数值按“TICKER_SYMBOL”分组，每组向上平移一行后的结果
df['target_REVENUE_Q1'] = df.groupby('TICKER_SYMBOL')['REVENUE_Q1'].shift(-1)
#shift(-1)是为了长度对齐
    
#groupby函数
#Pandas对象可以分成任何对象，可以通过多种方式来拆分对象，如：
    #[1]obj.groupby(‘key’)
    #[2]obj.groupby([‘key1’,’key2’])
    #[3]obj.groupby(key,axis=1)

#print (df.groupby('TICKER_SYMBOL').groups) #查看分组


#shift函数
#pandas DataFrame.shift()函数可以把数据移动指定的位数
    #period：表示移动的幅度，可以是正数，也可以是负数，默认值是1,1就表示移动一次，注意这里移动的都是数据，而索引是不移动的，移动之后没有对应值的，就赋值为NaN。
    #freq： DateOffset, timedelta, or time rule string，可选参数，默认值为None，只适用于时间序列，如果这个参数存在，那么会按照参数值移动时间索引，而数据值没有发生变化。
    #axis： {0, 1, ‘index', ‘columns'}，表示移动的方向，如果是0或者'index'表示上下移动，如果是1或者'columns'，则会左右移动。
    
df.head(10)

,TICKER_SYMBOL,END_DATE,C_RESER_CB,DEPOS_IN_OTH_BFI,PRECI_METALS,LOAN_TO_OTH_BANK_FI,TRADING_FA,DERIV_ASSETS,PUR_RESALE_FA,INT_RECEIV,...,DATA_VALUE2170726265,DATA_VALUE2170726266,DATA_VALUE2210200588,Unnamed: 0.1,Unnamed: 0.1.1,CLOSE_PRICE,TURNOVER_VOL,TURNOVER_VALUE,MARKET_VALUE,target_REVENUE_Q1
0,1,2008-12-31,3.976790e+10,2.150081e+10,9225000.0,9.236676e+09,4.144100e+07,290751000.0,3.473335e+10,1.605636e+09,...,4.753279,1.349286,10.376667,7.0,7.0,3.019333,9.124747e+08,9.579367e+09,2.776258e+10,3.760604e+09
1,1,2009-03-31,3.954528e+10,3.281080e+10,7080000.0,9.836695e+09,1.363916e+09,200250000.0,3.247499e+10,1.946312e+09,...,4.753279,1.349286,8.543333,8.0,8.0,4.658667,1.096579e+09,1.452570e+10,4.283428e+10,3.730246e+09
2,1,2009-06-30,4.222817e+10,2.081290e+10,5342000.0,7.998342e+09,1.785393e+09,162354000.0,3.795794e+10,1.711397e+09,...,4.753279,1.349286,7.883333,9.0,9.0,6.302333,8.111175e+08,1.525179e+10,5.794739e+10,3.623103e+09
3,1,2009-09-30,4.542918e+10,1.781418e+10,4694000.0,8.416666e+09,1.408176e+09,173611000.0,3.602692e+10,1.660956e+09,...,4.753279,1.349286,8.126667,10.0,10.0,7.248000,9.065716e+08,2.042128e+10,6.664261e+10,4.000487e+09
4,1,2009-12-31,5.424395e+10,1.559254e+10,3302000.0,5.361139e+09,1.132048e+09,99996000.0,4.092340e+10,1.625700e+09,...,4.753279,1.349286,8.073333,11.0,11.0,8.006000,5.768548e+08,1.390735e+10,7.360913e+10,4.084252e+09
5,1,2010-03-31,5.648850e+10,1.124296e+10,2946000.0,5.015728e+09,1.352405e+09,110577000.0,5.720913e+10,1.957240e+09,...,4.753279,1.349286,8.576667,12.0,12.0,7.582333,6.600740e+08,1.483008e+10,6.971699e+10,4.411859e+09
6,1,2010-06-30,6.150522e+10,8.844875e+09,2227000.0,5.318759e+09,5.431370e+08,201606000.0,5.496150e+10,2.006350e+09,...,4.753279,1.349286,8.826667,13.0,13.0,6.257333,6.777460e+08,1.309324e+10,5.974882e+10,4.640869e+09
7,1,2010-09-30,6.663149e+10,9.861586e+09,786000.0,7.810415e+09,5.540580e+08,320302000.0,7.361530e+10,2.243319e+09,...,4.753279,1.349286,8.736667,14.0,14.0,5.768667,2.340072e+08,4.103866e+09,5.952404e+10,4.834793e+09
8,1,2010-12-31,7.658686e+10,8.523729e+09,2000.0,8.475988e+09,1.000000e-05,371734000.0,9.826343e+10,2.121487e+09,...,4.753279,1.349286,9.160000,15.0,15.0,5.695667,8.653812e+08,1.550966e+10,5.876895e+10,5.815038e+09
9,1,2011-03-31,7.933548e+10,1.518595e+10,2000.0,7.141762e+09,2.020150e+09,464637000.0,1.369326e+11,2.876637e+09,...,4.753279,1.349286,9.403333,16.0,16.0,5.327333,5.586879e+08,8.945422e+09,5.497028e+10,6.322229e+09

In [65]:
df.shape #显示此时列数增加1(651 -> 652)

(768, 652)

In [50]:
df['target_REVENUE_Q1'].head(10)

0    3.760604e+09
1    3.730246e+09
2    3.623103e+09
3    4.000487e+09
4    4.084252e+09
5    4.411859e+09
6    4.640869e+09
7    4.834793e+09
8    5.815038e+09
9    6.322229e+09
Name: target_REVENUE_Q1, dtype: float64

In [76]:
pd.notnull(df['target_REVENUE_Q1']).sum()

740

In [75]:
pd.isnull(df['target_REVENUE_Q1']).sum()

28

In [36]:
#查看df的列名，请注意第0-1列和最后一列的名称
df.columns
    #第0-1列为'TICKER_SYMBOL', 'END_DATE'
    #最后一列为target_REVENUE_Q1

Index(['TICKER_SYMBOL', 'END_DATE', 'C_RESER_CB', 'DEPOS_IN_OTH_BFI',
       'PRECI_METALS', 'LOAN_TO_OTH_BANK_FI', 'TRADING_FA', 'DERIV_ASSETS',
       'PUR_RESALE_FA', 'INT_RECEIV',
       ...
       'DATA_VALUE2170726265', 'DATA_VALUE2170726266', 'DATA_VALUE2210200588',
       'Unnamed: 0.1', 'Unnamed: 0.1.1', 'CLOSE_PRICE', 'TURNOVER_VOL',
       'TURNOVER_VALUE', 'MARKET_VALUE', 'target_REVENUE_Q1'],
      dtype='object', length=652)

# 5.生成自变量和因变量

In [37]:
#基于df['target_REVENUE_Q1']生成X和Y
X = df[pd.notnull(df['target_REVENUE_Q1'])].iloc[:,2:-1].values
    #X不包括最后一列和前两列，即'TICKER_SYMBOL', 'END_DATE'，target_REVENUE_Q1
    #当需要选中所有行的某几列时，行参数可以省略，列参数需要指定，此时列参数前面必须带上“,:”，形如.loc[:,列参数]，.iloc[:,列参数]。
     #value生成numpy的array，不是dataframe类型
Y = df[pd.notnull(df['target_REVENUE_Q1'])].iloc[:,-1].values
    #Y只包含最后一列target_REVENUE_Q1

In [82]:
X.shape,Y.shape

((740, 649), (740,))

# 用随机森林计算特征的重要性

In [81]:
from sklearn.ensemble import RandomForestRegressor 
pro = 0.99 #累计重要性的选择比例
n_estimators =100 #树数量
max_features=0.8 #特征选择比例

    
rf = RandomForestRegressor(n_estimators = n_estimators,
                           max_features=max_features,
                           oob_score=True,
                           n_jobs=-1)
print(rf)

RandomForestRegressor(max_features=0.8, n_jobs=-1, oob_score=True)

In [ ]:
rf.fit(X, Y)

In [ ]:
names = df.iloc[:,2:-1].columns.values
names.shape

In [ ]:
#新定义一个数据框col_select
    #COL为列名
    #IMP为重要程度
    
col_select = pd.DataFrame({'COL':names,'IMP':rf.feature_importances_}).sort_values('IMP',ascending=False)
col_select.head()

# 新增特征重要度累计汇总列—CUM_IMP

In [ ]:
#在col_select中，新增一个汇总列————CUM_IMP
col_select['CUM_IMP'] = col_select['IMP'].cumsum()

pro = pro if col_select['IMP'][0:1].values[0]<pro else col_select['IMP'][0:1].values[0]

col_select = col_select[col_select['CUM_IMP']<=pro]

print('特征选择结果：%d个特征，占%.7f%%的重要性。'%(col_select.shape[0],pro*100))

In [ ]:
col_s = col_select['COL']
if(col_select[col_select['COL']=='MARKET_VALUE'].shape[0]==0):
    col_s = pd.Series('MARKET_VALUE').append(col_s)
if(col_select[col_select['COL']=='REVENUE_Q1'].shape[0]==0):
    col_s = pd.Series('REVENUE_Q1').append(col_s)
names_col = pd.Series(['TICKER_SYMBOL','END_DATE']).append(col_s).append(pd.Series('target_REVENUE_Q1'))
df = df[names_col]
df.head()

# 最终返回结果

In [ ]:
df.shape
#25+4个
    #'TICKER_SYMBOL', 'END_DATE'。'target_REVENUE_Q1'

In [ ]:
df.columns

In [ ]:
# df.to_csv("Data/df_bank.csv") 
    #不能在这里产生

In [ ]:
col_select.shape

In [ ]:
col_select