# Explore the Data

In [1]:
# Import the liraries
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# Inspect the datasets 
os.listdir("../data")

['users.csv',
 'data_by_genres.csv',
 'data_by_artist.csv',
 'data_by_year.csv',
 'data_w_genres.csv',
 'user_songs.csv',
 'spotify_data.csv',
 'user_friends.csv']

## Music Datasets

### 1.1 data_by_artist

In [3]:
# Load the data
data_by_artist = pd.read_csv("../data/data_by_artist.csv")

# Preview the data
data_by_artist.head()

,mode,count,acousticness,artists,danceability,duration_ms,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence,popularity,key
0,1,9,0.590111,"""Cats"" 1981 Original London Cast",0.467222,250318.555556,0.394003,0.011400,0.290833,-14.448000,0.210389,117.518111,0.389500,38.333333,5
1,1,26,0.862538,"""Cats"" 1983 Broadway Cast",0.441731,287280.000000,0.406808,0.081158,0.315215,-10.690000,0.176212,103.044154,0.268865,30.576923,5
2,1,7,0.856571,"""Fiddler On The Roof” Motion Picture Chorus",0.348286,328920.000000,0.286571,0.024593,0.325786,-15.230714,0.118514,77.375857,0.354857,34.857143,0
3,1,27,0.884926,"""Fiddler On The Roof” Motion Picture Orchestra",0.425074,262890.962963,0.245770,0.073587,0.275481,-15.639370,0.123200,88.667630,0.372030,34.851852,0
4,1,7,0.510714,"""Joseph And The Amazing Technicolor Dreamcoat""...",0.467143,270436.142857,0.488286,0.009400,0.195000,-10.236714,0.098543,122.835857,0.482286,43.000000,5

In [4]:
# Check the dimensions
print(f"Number of rows: {data_by_artist.shape[0]}\n"
      f"Number of columns: {data_by_artist.shape[1]}\n")

# Check for missing values
print(f"Number of missing values: \n{data_by_artist.isna().sum()}")

Number of rows: 28680
Number of columns: 15

Number of missing values:
mode                0
count               0
acousticness        0
artists             0
danceability        0
duration_ms         0
energy              0
instrumentalness    0
liveness            0
loudness            0
speechiness         0
tempo               0
valence             0
popularity          0
key                 0
dtype: int64

### 1.2 data_by_genres

In [5]:
# Load the data
data_by_genres = pd.read_csv("../data/data_by_genres.csv")

# Preview the data
data_by_genres.head()

,mode,genres,acousticness,danceability,duration_ms,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence,popularity,key
0,1,21st century classical,0.979333,0.162883,1.602977e+05,0.071317,0.606834,0.361600,-31.514333,0.040567,75.336500,0.103783,27.833333,6
1,1,432hz,0.494780,0.299333,1.048887e+06,0.450678,0.477762,0.131000,-16.854000,0.076817,120.285667,0.221750,52.500000,5
2,1,8-bit,0.762000,0.712000,1.151770e+05,0.818000,0.876000,0.126000,-9.180000,0.047000,133.444000,0.975000,48.000000,7
3,1,[],0.651417,0.529093,2.328809e+05,0.419146,0.205309,0.218696,-12.288965,0.107872,112.857352,0.513604,20.859882,7
4,1,a cappella,0.676557,0.538961,1.906285e+05,0.316434,0.003003,0.172254,-12.479387,0.082851,112.110362,0.448249,45.820071,7

In [6]:
# Check the dimensions
print(f"Number of rows: {data_by_genres.shape[0]}\n"
      f"Number of columns: {data_by_genres.shape[1]}\n")

# Check for missing values
print(f"Number of missing values: \n{data_by_genres.isna().sum()}")

Number of rows: 2973
Number of columns: 14

Number of missing values:
mode                0
genres              0
acousticness        0
danceability        0
duration_ms         0
energy              0
instrumentalness    0
liveness            0
loudness            0
speechiness         0
tempo               0
valence             0
popularity          0
key                 0
dtype: int64

### 1.3 data_by_year

In [7]:
# Load the data
data_by_year = pd.read_csv("../data/data_by_year.csv")

# Preview the data
data_by_year.head()

,mode,year,acousticness,danceability,duration_ms,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence,popularity,key
0,1,1921,0.886896,0.418597,260537.166667,0.231815,0.344878,0.205710,-17.048667,0.073662,101.531493,0.379327,0.653333,2
1,1,1922,0.938592,0.482042,165469.746479,0.237815,0.434195,0.240720,-19.275282,0.116655,100.884521,0.535549,0.140845,10
2,1,1923,0.957247,0.577341,177942.362162,0.262406,0.371733,0.227462,-14.129211,0.093949,114.010730,0.625492,5.389189,0
3,1,1924,0.940200,0.549894,191046.707627,0.344347,0.581701,0.235219,-14.231343,0.092089,120.689572,0.663725,0.661017,10
4,1,1925,0.962607,0.573863,184986.924460,0.278594,0.418297,0.237668,-14.146414,0.111918,115.521921,0.621929,2.604317,5

In [8]:
# Check the dimensions
print(f"Number of rows: {data_by_year.shape[0]}\n"
      f"Number of columns: {data_by_year.shape[1]}\n")

# Check for missing values
print(f"Number of missing values: \n{data_by_year.isna().sum()}")

Number of rows: 100
Number of columns: 14

Number of missing values:
mode                0
year                0
acousticness        0
danceability        0
duration_ms         0
energy              0
instrumentalness    0
liveness            0
loudness            0
speechiness         0
tempo               0
valence             0
popularity          0
key                 0
dtype: int64

### 1.4 data_w_genres

In [9]:
# Load the data
data_w_genres = pd.read_csv("../data/data_w_genres.csv")

# Preview the data
data_w_genres.head()

,genres,artists,acousticness,danceability,duration_ms,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence,popularity,key,mode,count
0,['show tunes'],"""Cats"" 1981 Original London Cast",0.590111,0.467222,250318.555556,0.394003,0.011400,0.290833,-14.448000,0.210389,117.518111,0.389500,38.333333,5,1,9
1,[],"""Cats"" 1983 Broadway Cast",0.862538,0.441731,287280.000000,0.406808,0.081158,0.315215,-10.690000,0.176212,103.044154,0.268865,30.576923,5,1,26
2,[],"""Fiddler On The Roof” Motion Picture Chorus",0.856571,0.348286,328920.000000,0.286571,0.024593,0.325786,-15.230714,0.118514,77.375857,0.354857,34.857143,0,1,7
3,[],"""Fiddler On The Roof” Motion Picture Orchestra",0.884926,0.425074,262890.962963,0.245770,0.073587,0.275481,-15.639370,0.123200,88.667630,0.372030,34.851852,0,1,27
4,[],"""Joseph And The Amazing Technicolor Dreamcoat""...",0.510714,0.467143,270436.142857,0.488286,0.009400,0.195000,-10.236714,0.098543,122.835857,0.482286,43.000000,5,1,7

In [10]:
# Check the dimensions
print(f"Number of rows: {data_w_genres.shape[0]}\n"
      f"Number of columns: {data_w_genres.shape[1]}\n")

# Check for missing values
print(f"Number of missing values: \n{data_w_genres.isna().sum()}")

Number of rows: 28680
Number of columns: 16

Number of missing values:
genres              0
artists             0
acousticness        0
danceability        0
duration_ms         0
energy              0
instrumentalness    0
liveness            0
loudness            0
speechiness         0
tempo               0
valence             0
popularity          0
key                 0
mode                0
count               0
dtype: int64

### 1.5 spotify_data

In [11]:
# Load the data
spotify_data = pd.read_csv("../data/spotify_data.csv")

# Preview the data
spotify_data.head()

,song_id,song_name,artist_id,artist_name,year,release_date,valence,acousticness,danceability,duration_ms,...,explicit,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,genre,popularity
0,4BJqT0PrAfrxzMOxytFOIz,"Piano Concerto No. 3 in D Minor, Op. 30: III. ...",9b149f96aa,Sergei Rachmaninoff,1921,1921,0.0594,0.982,0.279,831667,...,0,0.878000,10,0.665,-20.096,1,0.0366,80.954,"classical, post-romantic era, russian romantic...",4
1,7xPhfUan2yNtyFG0cUWkt8,Clancy Lowered the Boom,9d8adf100a,Dennis Day,1921,1921,0.9630,0.732,0.819,180533,...,0,0.000000,7,0.160,-12.441,1,0.4150,60.936,Unknown,5
2,1o6I8BglA6ylDMrIELygv1,Gati Bali,466b918be0,KHP Kridhamardawa Karaton Ngayogyakarta Hadini...,1921,1921,0.0394,0.961,0.328,500062,...,0,0.913000,3,0.101,-14.850,1,0.0339,110.339,Unknown,5
3,3ftBPsC5vPBKxYSee08FDH,Danny Boy,a8250f99cc,Frank Parker,1921,1921,0.1650,0.967,0.275,210000,...,0,0.000028,5,0.381,-9.316,1,0.0354,100.109,Unknown,3
4,4d6HGyGT8e121BsdKmw9v6,When Irish Eyes Are Smiling,c2a61e6015,Phil Regan,1921,1921,0.2530,0.957,0.418,166693,...,0,0.000002,3,0.229,-10.096,1,0.0380,101.665,Unknown,2

In [12]:
# Check the dimensions
print(f"Number of rows: {spotify_data.shape[0]}\n"
      f"Number of columns: {spotify_data.shape[1]}\n")

# Check for missing values
print(f"Number of missing values: \n{spotify_data.isna().sum()}")

Number of rows: 170653
Number of columns: 21

Number of missing values:
song_id              0
song_name            0
artist_id            0
artist_name         12
year                 0
release_date         0
valence              0
acousticness         0
danceability         0
duration_ms          0
energy               0
explicit             0
instrumentalness     0
key                  0
liveness             0
loudness             0
mode                 0
speechiness          0
tempo                0
genre                0
popularity           0
dtype: int64

## User Data

### 2.1 users

In [13]:
# Load the data
users = pd.read_csv("../data/users.csv")

# Preview the data
users.head()

,user_id,first_name,last_name,age,sex,portrait_graph
0,2dc0cb6c-d4f7-4a95-a9b2-daede98e819a,Nichole,Wolf,47,F,user_1.png
1,0d1905e1-91b7-4a27-b804-9c975c105ce3,Jason,Golden,29,M,user_2.png
2,835564e4-eada-4e91-879f-7eadc24f5bb4,Katherine,Snyder,27,F,user_3.png
3,b136d87d-8d51-4a9d-b655-29fb3bc816b8,Robert,Marsh,48,M,user_4.png
4,19678c5c-9d86-4c9e-a0e4-4fa173a8bb5a,Tonya,Hart,58,F,user_5.png

In [14]:
# Check the dimensions
print(f"Number of rows: {users.shape[0]}\n"
      f"Number of columns: {users.shape[1]}\n")

# Check for missing values
print(f"Number of missing values: \n{users.isna().sum()}")

Number of rows: 2000
Number of columns: 6

Number of missing values:
user_id           0
first_name        0
last_name         0
age               0
sex               0
portrait_graph    0
dtype: int64

### 2.2 user_songs

In [15]:
# Load the data
user_songs = pd.read_csv("../data/user_songs.csv")

# Preview the data
user_songs.head()

,user_id,song_id,listening_count
0,baefc413-5ca5-40d4-b85e-000e2e80a003,0h083GWZ2W5scJM6JgwETQ,3
1,4da237ee-f206-4a74-866b-04c3c19ecef0,3QWlqqpc4EOm52xipzSehQ,3
2,9f10a3cb-6cd2-4d0a-8318-8f7eba13ec05,174BJkBMuLak3wSvYHASpo,9
3,b71a3b34-0f5f-4018-af95-95ccdb1a1bf9,0LCgPftb1BoxaAmKe8RwY8,1
4,5a5631d5-fdd6-461c-9f06-72de9fb76062,2WinyCfKidqagBGRVPtsTR,27

In [16]:
# Check the dimensions
print(f"Number of rows: {user_songs.shape[0]}\n"
      f"Number of columns: {user_songs.shape[1]}\n")

# Check for missing values
print(f"Number of missing values: \n{user_songs.isna().sum()}")

Number of rows: 10000
Number of columns: 3

Number of missing values:
user_id            0
song_id            0
listening_count    0
dtype: int64

### 2.3 user_friends

In [17]:
# Load the data
user_friends = pd.read_csv("../data/user_friends.csv")

# Preview the data
user_friends.head()

                                user_id                             friend_id
0  dff6f67f-6de5-4a0a-85cc-47b7c0d76cf3  07a9ecf4-e76a-46a7-8901-56f2cf142cdc
1  19c210f8-693d-4824-a9e2-7d9c6494b0a0  325a00b8-db7e-49e1-9a40-caf503cf99c5
2  5a5631d5-fdd6-461c-9f06-72de9fb76062  6ddbd57a-cb18-4c1a-9dd7-1569c51621f8
3  79714cee-9768-4721-999a-0444b7db6705  1a855f68-9edd-4523-87ee-beeb27a7274c
4  93dd8a29-5472-46fe-8fd8-28c4ffb4ea51  32e38ea8-4052-49ba-afd9-cc22db17178a

In [18]:
# Check the dimensions
print(f"Number of rows: {user_friends.shape[0]}\n"
      f"Number of columns: {user_friends.shape[1]}\n")

# Check for missing values
print(f"Number of missing values: \n{user_friends.isna().sum()}")

Number of rows: 24000
Number of columns: 2

Number of missing values:
user_id      0
friend_id    0
dtype: int64